name: Sync Obsidian Posts
on:
  repository_dispatch:
    types: [obsidian-update]
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  sync-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout blog repo
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Checkout obsidian vault
      uses: actions/checkout@v4
      with:
        repository: psantalla/obsidian-vault-private
        token: ${{ secrets.OBSIDIAN_VAULT_TOKEN }}
        path: temp-obsidian-vault

    - name: Clean vault git data
      run: rm -rf temp-obsidian-vault/.git

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Sync posts from Obsidian
      run: |
        # Copy new/updated posts from Obsidian
        if [ -d "temp-obsidian-vault/Public thoughts" ]; then
          find "temp-obsidian-vault/Public thoughts" -name "*.md" -exec cp {} content/blog/ \; 2>/dev/null || true
          find "temp-obsidian-vault/Public thoughts" -name "*.png" -exec cp {} content/blog/ \; 2>/dev/null || true
          find "temp-obsidian-vault/Public thoughts" -name "*.jpg" -exec cp {} content/blog/ \; 2>/dev/null || true
          find "temp-obsidian-vault/Public thoughts" -name "*.jpeg" -exec cp {} content/blog/ \; 2>/dev/null || true
          find "temp-obsidian-vault/Public thoughts" -name "*.gif" -exec cp {} content/blog/ \; 2>/dev/null || true
          find "temp-obsidian-vault/Public thoughts" -name "*.webp" -exec cp {} content/blog/ \; 2>/dev/null || true
        fi

    - name: Fix problematic image filenames
      run: |
        find content/blog -name "*.png" -o -name "*.jpg" -o -name "*.jpeg" -o -name "*.gif" -o -name "*.webp" | while read file; do
          if [ -f "$file" ]; then
            dir=$(dirname "$file")
            basename=$(basename "$file")
            extension="${basename##*.}"
            filename="${basename%.*}"

            if [[ "$filename" =~ [^a-zA-Z0-9._-] ]]; then
              safe_name=$(echo "$filename" | sed 's/[^a-zA-Z0-9._-]/-/g' | sed 's/--*/-/g' | sed 's/^-\|-$//g' | tr '[:upper:]' '[:lower:]')
              new_file="$dir/${safe_name}.${extension}"

              echo "Renaming: $basename -> ${safe_name}.${extension}"
              mv "$file" "$new_file"

              find content/blog -name "*.md" -exec sed -i "s|$basename|${safe_name}.${extension}|g" {} \;
            fi
          fi
        done

    - name: Build site
      run: npm run build

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .

        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Auto-sync from Obsidian: $(date)"
          git push
        fi
