name: Sync Obsidian Posts
on:
  repository_dispatch:
    types: [obsidian-update]
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  sync-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout blog repo
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Checkout obsidian vault
      uses: actions/checkout@v4
      with:
        repository: psantalla/obsidian-vault-private
        token: ${{ secrets.OBSIDIAN_VAULT_TOKEN }}
        path: temp-obsidian-vault

    - name: Clean vault git data
      run: rm -rf temp-obsidian-vault/.git

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Sync posts from Obsidian
      run: |
        if [ -d "temp-obsidian-vault/Public thoughts" ]; then
          find "temp-obsidian-vault/Public thoughts" -name "*.md" -exec cp {} content/blog/ \; 2>/dev/null || true
          find "temp-obsidian-vault/Public thoughts" -name "*.png" -exec cp {} content/blog/ \; 2>/dev/null || true
          find "temp-obsidian-vault/Public thoughts" -name "*.jpg" -exec cp {} content/blog/ \; 2>/dev/null || true
          find "temp-obsidian-vault/Public thoughts" -name "*.jpeg" -exec cp {} content/blog/ \; 2>/dev/null || true
          find "temp-obsidian-vault/Public thoughts" -name "*.gif" -exec cp {} content/blog/ \; 2>/dev/null || true
          find "temp-obsidian-vault/Public thoughts" -name "*.webp" -exec cp {} content/blog/ \; 2>/dev/null || true
        fi

    - name: Build site
      run: npm run build

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Auto-sync from Obsidian: $(date)"
          git pull origin main --rebase
          git push origin main
        fi
