name: Sync Obsidian Posts

on:
  repository_dispatch:
    types: [obsidian-update]
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  sync-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout blog repo
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Checkout obsidian vault
      uses: actions/checkout@v4
      with:
        repository: psantalla/obsidian-vault-private
        token: ${{ secrets.OBSIDIAN_VAULT_TOKEN }}
        path: obsidian-vault

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Sync posts from Obsidian
      run: |
        mkdir -p content/blog/obsidian-posts

        if [ -d "obsidian-vault/Public thoughts" ]; then
          cp -r "obsidian-vault/Public thoughts/"* content/blog/obsidian-posts/ 2>/dev/null || true
        fi

        if git diff --quiet && git diff --staged --quiet; then
          echo "No changes detected"
          exit 0
        fi

    - name: Build site
      run: npm run build

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Auto-sync from Obsidian: $(date)" || exit 0
        git push
